/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ui;

import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.DetallePrestamo;
import model.Prestamo;
import services.PrestamoService;
import java.text.SimpleDateFormat;

/**
 *
 * @author herma
 */
public class EditarPrestamoDialog extends javax.swing.JDialog {
    
    private PrestamoService prestamoService;
    private Prestamo prestamo;
    private boolean actualizado = false;

    /**
     * Constructor con los parámetros necesarios
     * @param parent Ventana padre
     * @param modal Si es modal
     * @param prestamo El préstamo a editar
     */
    public EditarPrestamoDialog(java.awt.Frame parent, boolean modal, model.Prestamo prestamo) {
        super(parent, modal);
        initComponents();
        this.prestamo = prestamo;
        this.prestamoService = new PrestamoService();
        setLocationRelativeTo(parent);
        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpPrincipal = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblNombreCliente = new javax.swing.JLabel();
        lblListaLibros = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbLibrosPrestados = new javax.swing.JTable();
        txtNombreCliente = new javax.swing.JTextField();
        lblFechaPrestamo = new javax.swing.JLabel();
        lblListaLibros2 = new javax.swing.JLabel();
        txtFechaPrestamo = new javax.swing.JTextField();
        dtFechaPrestamo = new com.toedter.calendar.JDateChooser();
        btnGuardar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jpPrincipal.setBackground(java.awt.SystemColor.activeCaption);

        lblTitulo.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setText("Editar prestamos");

        lblNombreCliente.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        lblNombreCliente.setText("Nombres:");

        lblListaLibros.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        lblListaLibros.setText("Libros prestados:");

        tbLibrosPrestados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbLibrosPrestados);

        txtNombreCliente.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N

        lblFechaPrestamo.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        lblFechaPrestamo.setText("Fecha prestamo:");

        lblListaLibros2.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        lblListaLibros2.setText("Fecha prestamo:");

        txtFechaPrestamo.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N

        btnGuardar.setBackground(new java.awt.Color(245, 222, 179));
        btnGuardar.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(245, 222, 179));
        btnSalir.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpPrincipalLayout = new javax.swing.GroupLayout(jpPrincipal);
        jpPrincipal.setLayout(jpPrincipalLayout);
        jpPrincipalLayout.setHorizontalGroup(
            jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(114, 114, 114))
            .addGroup(jpPrincipalLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPrincipalLayout.createSequentialGroup()
                        .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpPrincipalLayout.createSequentialGroup()
                                .addComponent(lblNombreCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblListaLibros)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(jpPrincipalLayout.createSequentialGroup()
                        .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jpPrincipalLayout.createSequentialGroup()
                                .addComponent(lblFechaPrestamo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFechaPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpPrincipalLayout.createSequentialGroup()
                                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblListaLibros2)
                                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dtFechaPrestamo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))))
        );
        jpPrincipalLayout.setVerticalGroup(
            jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPrincipalLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblTitulo)
                .addGap(32, 32, 32)
                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreCliente)
                    .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblListaLibros)
                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPrincipalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFechaPrestamo)
                            .addComponent(txtFechaPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblListaLibros2)
                            .addComponent(dtFechaPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 91, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPrincipalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        guardarCambios();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed
    
    private void cargarDatos() {
        // Crear formateador de fechas
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        
        // Cargar datos del cliente
        txtNombreCliente.setText(prestamo.getNombreCliente());
        txtNombreCliente.setEditable(false);
        txtNombreCliente.setBackground(new java.awt.Color(240, 240, 240));
        
        String fechaPrestamoStr = sdf.format(prestamo.getFechaPrestamo());
        txtFechaPrestamo.setText(fechaPrestamoStr);
        txtFechaPrestamo.setEditable(false);
        txtFechaPrestamo.setBackground(new java.awt.Color(240, 240, 240)); 
    
        dtFechaPrestamo.setDate(prestamo.getFechaDevolucionEsperada());
        
        // Configurar tabla de libros prestados
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new String[]{"ID", "Título", "Estado"});
        tbLibrosPrestados.setModel(model);
        
        if (prestamo.getDetalles() != null) {
            for (DetallePrestamo detalle : prestamo.getDetalles()) {
                model.addRow(new Object[]{
                    detalle.getIdLibro(),
                    detalle.getTituloLibro(),
                    detalle.getEstadoLibro()
                });
            }
        }
        
        // Ajustar ancho de columnas
        tbLibrosPrestados.getColumnModel().getColumn(0).setPreferredWidth(50);
        tbLibrosPrestados.getColumnModel().getColumn(1).setPreferredWidth(150);
        tbLibrosPrestados.getColumnModel().getColumn(2).setPreferredWidth(80);
    }
    
    private boolean validarFecha() {
        Date nuevaFecha = dtFechaPrestamo.getDate();
        if (nuevaFecha == null) {
            JOptionPane.showMessageDialog(this, "Seleccione una fecha válida");
            return false;
        }
        
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        String fechaHoy = sdf.format(new Date());
    
        if (nuevaFecha.before(new Date())) {
            JOptionPane.showMessageDialog(this, "La fecha no puede ser anterior a hoy (" + fechaHoy + ")");
            return false;
        }
        return true;
    }
    
    private void guardarCambios() {
        if (!validarFecha()) return;

        Date nuevaFecha = dtFechaPrestamo.getDate();
        
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        String fechaFormateada = sdf.format(nuevaFecha);

        int confirm = JOptionPane.showConfirmDialog(this,
            "¿Actualizar fecha de devolución a " + fechaFormateada + "?",
            "Confirmar",
            JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            try {
                boolean exito = prestamoService.actualizarFechaDevolucion(
                    prestamo.getId(), nuevaFecha);

                if (exito) {
                    JOptionPane.showMessageDialog(this, 
                        "Fecha actualizada exitosamente",
                        "Éxito", JOptionPane.INFORMATION_MESSAGE);
                    actualizado = true;
                    dispose();  // Cierra el diálogo después de guardar
                } else {
                    JOptionPane.showMessageDialog(this, 
                        "Error al actualizar la fecha",
                        "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, 
                    "Error: " + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
    public boolean isActualizado() {
        return actualizado;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSalir;
    private com.toedter.calendar.JDateChooser dtFechaPrestamo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpPrincipal;
    private javax.swing.JLabel lblFechaPrestamo;
    private javax.swing.JLabel lblListaLibros;
    private javax.swing.JLabel lblListaLibros2;
    private javax.swing.JLabel lblNombreCliente;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tbLibrosPrestados;
    private javax.swing.JTextField txtFechaPrestamo;
    private javax.swing.JTextField txtNombreCliente;
    // End of variables declaration//GEN-END:variables
}
