/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.awt.Frame;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author herma
 */
public class HomeFrame extends javax.swing.JFrame {

    /**
     * Creates new form HomeFrame
     */
    public HomeFrame() {
        initComponents();
        setLocationRelativeTo(null); 
        setTitle("Sistema de Biblioteca - Dashboard");
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mnPrincipal = new javax.swing.JMenuBar();
        mnCliente = new javax.swing.JMenu();
        mnLibro = new javax.swing.JMenu();
        mnPrestamo = new javax.swing.JMenu();
        mnCerrarSesion = new javax.swing.JMenu();

        jPanel1.setBackground(java.awt.SystemColor.activeCaption);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 757, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );

        mnPrincipal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        mnCliente.setText("Clientes");
        mnCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnCliente.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        mnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnClienteActionPerformed(evt);
            }
        });
        mnPrincipal.add(mnCliente);

        mnLibro.setText("Libros");
        mnLibro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnLibro.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        mnLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLibroActionPerformed(evt);
            }
        });
        mnPrincipal.add(mnLibro);

        mnPrestamo.setText("Prestamos");
        mnPrestamo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnPrestamo.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        mnPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPrestamoActionPerformed(evt);
            }
        });
        mnPrincipal.add(mnPrestamo);

        mnCerrarSesion.setText("Cerrar Sesión");
        mnCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCerrarSesionActionPerformed(evt);
            }
        });
        mnPrincipal.add(mnCerrarSesion);

        setJMenuBar(mnPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnClienteActionPerformed
        for (Frame frame : JFrame.getFrames()) {
            if (frame instanceof ClienteFrame && frame.isVisible()) {
                frame.toFront();
                return;
            }
        }
        // Crear nueva instancia
        ClienteFrame clientesFrame = new ClienteFrame();
        clientesFrame.setVisible(true);
    }//GEN-LAST:event_mnClienteActionPerformed

    private void mnLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnLibroActionPerformed

    private void mnPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPrestamoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnPrestamoActionPerformed

    private void mnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCerrarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnCerrarSesionActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu mnCerrarSesion;
    private javax.swing.JMenu mnCliente;
    private javax.swing.JMenu mnLibro;
    private javax.swing.JMenu mnPrestamo;
    private javax.swing.JMenuBar mnPrincipal;
    // End of variables declaration//GEN-END:variables
}
